// These styles apply to every route in the application
import "./global.css";

import Head from "next/head";
import { Nav } from "../components/Nav";
import { ProfileCard } from "../components/ProfileCard";

const GlobalLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main>
        <ProfileCard />
        {children}
      </main>
    </>
  );
};

export default GlobalLayout;
