import {
  Github,
  Tumblr,
  Twitch,
  Twitter,
} from "@icons-pack/react-simple-icons";

import Head from "next/head";
import Link from "next/link";
import { Nav } from "../components/Nav";
import type { NextPage } from "next";
import { ProfileCard } from "../components/ProfileCard";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main>
        <ProfileCard />
        <section>
          <h2>Where to find me on the web</h2>
          <ul className="social-links">
            <li>
              <Twitter />{" "}
              <a rel="me" href="https://twitter.com/essentialrandom">
                Twitter
              </a>
            </li>
            <li>
              <Tumblr />
              <a rel="me" href="https://essential-randomness.tumblr.com/">
                Tumblr
              </a>
            </li>
            <li>
              <Github />
              <a rel="me" href="https://github.com/essential-randomness">
                GitHub
              </a>
            </li>
            <li>
              <Twitch />
              <a rel="me" href="https://www.twitch.tv/essentialrandomness">
                Twitch
              </a>
            </li>
          </ul>
        </section>
      </main>
    </>
  );
};

export default Home;
