import Head from "next/head";
import { Nav } from "../components/Nav";
import type { NextPage } from "next";
import { PayPalButton } from "../components/PayPalButton";
import { ProfileCard } from "../components/ProfileCard";
import React from "react";
import Script from "next/script";

const SupportMe: NextPage = () => {
  const [quantity, setQuantity] = React.useState(5);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main>
        <input
          id="donation-5"
          type="radio"
          name="donation"
          value={5}
          checked={quantity == 5}
          onChange={() => setQuantity(5)}
        />
        <label htmlFor="donation-5">$5/month</label>
        <input
          id="donation-10"
          type="radio"
          name="donation"
          value={10}
          checked={quantity == 10}
          onChange={() => setQuantity(10)}
        />
        <label htmlFor="donation-10">$10/month</label>
        <input
          id="donation-15"
          type="radio"
          name="donation"
          value={15}
          checked={quantity == 15}
          onChange={() => setQuantity(15)}
        />
        <label htmlFor="donation-15">$15/month</label>
        <PayPalButton planId="P-2T800313EX3963603MMBL4MI" quantity={quantity} />
      </main>
    </>
  );
};

export default SupportMe;
